language: cpp

compiler:
  - clang
  - gcc

before_install:
  # CMake
  - sudo add-apt-repository --yes ppa:george-edison55/precise-backports
  - sudo apt-get update -qq

install:
  # CMake
  - sudo apt-get install -q cmake cmake-data
  - sudo apt-get install -y libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

before_script: cmake CMakeLists.txt

script:
  - $CXX --version
  - make
  - make test
