language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - C_CXX=g++-4.9
        - C_CC=gcc-4.9

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - C_CXX=g++-5
        - C_CC=gcc-5

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - C_CXX=g++-6
        - C_CC=gcc-6
        
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env:
        - C_CXX=clang++-3.5
        - C_CC=clang-3.5

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env:
        - C_CXX=clang++-3.6
        - C_CC=clang-3.6
        
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env:
        - C_CXX=clang++-3.7
        - C_CC=clang-3.7
        
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - C_CXX=clang++-3.8
        - C_CC=clang-3.8
        
# Activate when we are allowed to use MacOS X
#    - os: osx
#      compiler: clang
#      env:
#        - C_CXX=clang++
#        - C_CC=clang

before_install:
  # CMake
  - wget -q https://cmake.org/files/v3.7/cmake-3.7.1.tar.gz
  - sudo apt-get update -qq

install:
  # CMake
  - sudo apt-get install build-essential
  - tar xzf cmake-3.7.1.tar.gz
  - "cd cmake-3.7.1 && ./configure && make && sudo make install ; cd -"
  # GTest
  - sudo apt-get install -y libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/local/lib/ ; cd -"

before_script:
  - CXX=$C_CXX CC=$C_CC cmake .

script:
  - sudo make
  - sudo make test
